services:
  tggod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tggod
    ports:
      - "8080:80"
    volumes:
      # 数据库文件挂载
      - ./data:/app/data
      # 媒体文件挂载
      - ./media:/app/media
      # 日志文件挂载
      - ./logs:/app/logs
      # Telegram会话文件挂载
      - ./telegram_sessions:/app/telegram_sessions
    environment:
      - TZ=Asia/Shanghai
      - DATABASE_URL=sqlite:////app/data/tggod.db
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SECRET_KEY=${SECRET_KEY}
      - MEDIA_ROOT=/app/media
      - LOG_FILE=/app/logs/app.log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
    driver: local
  media:
    driver: local
  logs:
    driver: local
  telegram_sessions:
    driver: local