"""add_sync_tracking_fields_to_filter_rule

Revision ID: a1b2c3d4e5f6
Revises: 80ebcc3a68d1
Create Date: 2025-07-26 16:35:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '80ebcc3a68d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filter_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_sync_time', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_sync_message_count', sa.Integer(), nullable=True, default=0))
        batch_op.add_column(sa.Column('sync_status', sa.String(length=20), nullable=True, default='pending'))
        batch_op.add_column(sa.Column('needs_full_resync', sa.Boolean(), nullable=True, default=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filter_rules', schema=None) as batch_op:
        batch_op.drop_column('needs_full_resync')
        batch_op.drop_column('sync_status')
        batch_op.drop_column('last_sync_message_count')
        batch_op.drop_column('last_sync_time')

    # ### end Alembic commands ###