"""add_scheduling_fields_to_download_task

Revision ID: b2c3d4e5f6g7
Revises: a1b2c3d4e5f6
Create Date: 2025-07-26 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'b2c3d4e5f6g7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_type', sa.String(length=20), nullable=True, default='once'))
        batch_op.add_column(sa.Column('schedule_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('schedule_config', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('next_run_time', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_run_time', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True, default=True))
        batch_op.add_column(sa.Column('max_runs', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('run_count', sa.Integer(), nullable=True, default=0))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_tasks', schema=None) as batch_op:
        batch_op.drop_column('run_count')
        batch_op.drop_column('max_runs')
        batch_op.drop_column('is_active')
        batch_op.drop_column('last_run_time')
        batch_op.drop_column('next_run_time')
        batch_op.drop_column('schedule_config')
        batch_op.drop_column('schedule_type')
        batch_op.drop_column('task_type')

    # ### end Alembic commands ###