"""add download_records table

Revision ID: 5b9a1e4e8161
Revises: 2a66b1fee065
Create Date: 2025-07-25 20:39:10.477922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b9a1e4e8161'
down_revision = '2a66b1fee065'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('local_file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('message_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('download_status', sa.String(length=50), nullable=True),
    sa.Column('download_progress', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('download_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('download_completed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['download_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_records_id'), 'download_records', ['id'], unique=False)
    op.add_column('download_tasks', sa.Column('date_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('download_tasks', sa.Column('date_to', sa.DateTime(timezone=True), nullable=True))
    op.add_column('telegram_messages', sa.Column('media_group_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_telegram_messages_media_group_id'), 'telegram_messages', ['media_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_messages_media_group_id'), table_name='telegram_messages')
    op.drop_column('telegram_messages', 'media_group_id')
    op.drop_column('download_tasks', 'date_to')
    op.drop_column('download_tasks', 'date_from')
    op.drop_index(op.f('ix_download_records_id'), table_name='download_records')
    op.drop_table('download_records')
    # ### end Alembic commands ###