"""add is_own_message field

Revision ID: 603e81765e8a
Revises: ef08cb95a96a
Create Date: 2025-07-11 09:19:26.435500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603e81765e8a'
down_revision = 'ef08cb95a96a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_messages', sa.Column('is_own_message', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_messages', 'is_own_message')
    # ### end Alembic commands ###