"""添加媒体文件按需下载支持字段

Revision ID: 816072c24709
Revises: 603e81765e8a
Create Date: 2025-07-11 13:35:41.208639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816072c24709'
down_revision = '603e81765e8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_messages', sa.Column('media_file_id', sa.String(length=255), nullable=True))
    op.add_column('telegram_messages', sa.Column('media_file_unique_id', sa.String(length=255), nullable=True))
    op.add_column('telegram_messages', sa.Column('media_downloaded', sa.Boolean(), nullable=True))
    op.add_column('telegram_messages', sa.Column('media_download_url', sa.String(length=500), nullable=True))
    op.add_column('telegram_messages', sa.Column('media_download_error', sa.Text(), nullable=True))
    op.add_column('telegram_messages', sa.Column('media_thumbnail_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_messages', 'media_thumbnail_path')
    op.drop_column('telegram_messages', 'media_download_error')
    op.drop_column('telegram_messages', 'media_download_url')
    op.drop_column('telegram_messages', 'media_downloaded')
    op.drop_column('telegram_messages', 'media_file_unique_id')
    op.drop_column('telegram_messages', 'media_file_id')
    # ### end Alembic commands ###