"""add jellyfin configuration fields to download tasks

Revision ID: 8a1d14e65d0b
Revises: 5b9a1e4e8161
Create Date: 2025-07-25 21:48:05.302918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a1d14e65d0b'
down_revision = '5b9a1e4e8161'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download_tasks', sa.Column('use_jellyfin_structure', sa.Boolean(), nullable=True))
    op.add_column('download_tasks', sa.Column('include_metadata', sa.Boolean(), nullable=True))
    op.add_column('download_tasks', sa.Column('download_thumbnails', sa.Boolean(), nullable=True))
    op.add_column('download_tasks', sa.Column('use_series_structure', sa.Boolean(), nullable=True))
    op.add_column('download_tasks', sa.Column('organize_by_date', sa.Boolean(), nullable=True))
    op.add_column('download_tasks', sa.Column('max_filename_length', sa.Integer(), nullable=True))
    op.add_column('download_tasks', sa.Column('thumbnail_size', sa.String(length=20), nullable=True))
    op.add_column('download_tasks', sa.Column('poster_size', sa.String(length=20), nullable=True))
    op.add_column('download_tasks', sa.Column('fanart_size', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('download_tasks', 'fanart_size')
    op.drop_column('download_tasks', 'poster_size')
    op.drop_column('download_tasks', 'thumbnail_size')
    op.drop_column('download_tasks', 'max_filename_length')
    op.drop_column('download_tasks', 'organize_by_date')
    op.drop_column('download_tasks', 'use_series_structure')
    op.drop_column('download_tasks', 'download_thumbnails')
    op.drop_column('download_tasks', 'include_metadata')
    op.drop_column('download_tasks', 'use_jellyfin_structure')
    # ### end Alembic commands ###