"""Add forwarded message details

Revision ID: da3b11571a94
Revises: 816072c24709
Create Date: 2025-07-12 09:37:09.667756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da3b11571a94'
down_revision = '816072c24709'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_messages', sa.Column('forwarded_from_id', sa.BigInteger(), nullable=True))
    op.add_column('telegram_messages', sa.Column('forwarded_from_type', sa.String(length=20), nullable=True))
    op.add_column('telegram_messages', sa.Column('forwarded_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_messages', 'forwarded_date')
    op.drop_column('telegram_messages', 'forwarded_from_type')
    op.drop_column('telegram_messages', 'forwarded_from_id')
    # ### end Alembic commands ###