"""Add message extended fields

Revision ID: ef08cb95a96a
Revises: d4cde2b7bf4a
Create Date: 2025-07-09 10:17:35.808801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef08cb95a96a'
down_revision = 'd4cde2b7bf4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_messages', sa.Column('reply_to_message_id', sa.BigInteger(), nullable=True))
    op.add_column('telegram_messages', sa.Column('edit_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('telegram_messages', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    op.add_column('telegram_messages', sa.Column('reactions', sa.JSON(), nullable=True))
    op.add_column('telegram_messages', sa.Column('mentions', sa.JSON(), nullable=True))
    op.add_column('telegram_messages', sa.Column('hashtags', sa.JSON(), nullable=True))
    op.add_column('telegram_messages', sa.Column('urls', sa.JSON(), nullable=True))
    op.add_column('telegram_messages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_messages', 'updated_at')
    op.drop_column('telegram_messages', 'urls')
    op.drop_column('telegram_messages', 'hashtags')
    op.drop_column('telegram_messages', 'mentions')
    op.drop_column('telegram_messages', 'reactions')
    op.drop_column('telegram_messages', 'is_pinned')
    op.drop_column('telegram_messages', 'edit_date')
    op.drop_column('telegram_messages', 'reply_to_message_id')
    # ### end Alembic commands ###